/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoLightsUI;

import Analysis.Abnormalities;
import Analysis.GetDBData;
import Analysis.Graph;
import Analysis.paintGraph;
import java.awt.Graphics;

/**
 *
 * @author Mido Austin
 */
public class Analysis extends javax.swing.JFrame {

    /**
     * Creates new form Analysis
     */
    public Analysis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        J1Graph = new javax.swing.JButton();
        J2Graph = new javax.swing.JButton();
        J3Graph = new javax.swing.JButton();
        abnormal = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Weekly Intersection Analysis");
        title.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        J1Graph.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        J1Graph.setText("J1 Graphical Analysis");
        J1Graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J1GraphActionPerformed(evt);
            }
        });

        J2Graph.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        J2Graph.setText("J2 Graphical Analysis");
        J2Graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J2GraphActionPerformed(evt);
            }
        });

        J3Graph.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        J3Graph.setText("J3 Graphical Analysis");
        J3Graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J3GraphActionPerformed(evt);
            }
        });

        abnormal.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        abnormal.setText("Abnormalities To Consider");
        abnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abnormalActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        back.setText("RETURN");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(J1Graph, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J2Graph, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J3Graph, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(abnormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(J2Graph, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(J1Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(J3Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abnormal, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGap(74, 74, 74)
                .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void J1GraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J1GraphActionPerformed
        GetDBData dbdata = new GetDBData(1);
        new paintGraph().junction=1;
        Graph graph = new Graph();
        this.setVisible(false);
    }//GEN-LAST:event_J1GraphActionPerformed

    private void J2GraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J2GraphActionPerformed
        GetDBData dbdata2 = new GetDBData(2);
        Graph graph = new Graph();
        this.setVisible(false);
    }//GEN-LAST:event_J2GraphActionPerformed

    private void J3GraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J3GraphActionPerformed
        GetDBData dbdata3= new GetDBData(3);
        Graph graph = new Graph();
        this.setVisible(false);
    }//GEN-LAST:event_J3GraphActionPerformed

    private void abnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abnormalActionPerformed
        new Abnormalities().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_abnormalActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Management().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analysis().setVisible(true);
            }
        });
    }
    Graphics g;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton J1Graph;
    private javax.swing.JButton J2Graph;
    private javax.swing.JButton J3Graph;
    private javax.swing.JButton abnormal;
    private javax.swing.JButton back;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    public static class Events {

        public Events() {
        }
    }
}
