/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoLightsUI;

import autolightstests.PrintTest;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mido Austin
 */
public class DailyCountsData extends javax.swing.JFrame {

    /**
     * Creates new form DailyCountsData
     */
    public DailyCountsData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("autolightsdb?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        MondayQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DailyCounts d WHERE d.day like 'Monday'");
        MondayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : MondayQuery.getResultList();
        TuesdayQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DailyCounts d WHERE d.day like 'Tuesday'");
        TuesdayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : TuesdayQuery.getResultList();
        WednesdayQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DailyCounts d WHERE d.day like 'Wednesday'");
        WednesdayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : WednesdayQuery.getResultList();
        ThursdayQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DailyCounts d WHERE d.day like 'Thursday'");
        ThursdayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ThursdayQuery.getResultList();
        FridayQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DailyCounts d WHERE d.day like 'Friday'");
        FridayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : FridayQuery.getResultList();
        SaturdayQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DailyCounts d WHERE d.day like 'Saturday'");
        SaturdayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : SaturdayQuery.getResultList();
        dailyCountsQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DailyCounts d");
        dailyCountsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dailyCountsQuery.getResultList();
        dailyCountsQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DailyCounts d");
        dailyCountsList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dailyCountsQuery1.getResultList();
        entityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("autolightsdb2?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        mondayQuery = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT m FROM Monday m");
        mondayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : mondayQuery.getResultList();
        tuesdayQuery = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT t FROM Tuesday t");
        tuesdayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tuesdayQuery.getResultList();
        wednesdayQuery = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT w FROM Wednesday w");
        wednesdayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : wednesdayQuery.getResultList();
        thursdayQuery = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT t FROM Thursday t");
        thursdayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : thursdayQuery.getResultList();
        fridayQuery = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT f FROM Friday f");
        fridayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : fridayQuery.getResultList();
        saturdayQuery = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT s FROM Saturday s");
        saturdayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : saturdayQuery.getResultList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        MondayPane = new javax.swing.JScrollPane();
        MonCounts = new javax.swing.JTable();
        TuesdsyPane = new javax.swing.JScrollPane();
        TueCounts = new javax.swing.JTable();
        WednesdayPane = new javax.swing.JScrollPane();
        WedCounts = new javax.swing.JTable();
        ThursdayPane = new javax.swing.JScrollPane();
        ThuCounts = new javax.swing.JTable();
        FridayPane = new javax.swing.JScrollPane();
        FriCounts = new javax.swing.JTable();
        SaturdayPane = new javax.swing.JScrollPane();
        SatCounts = new javax.swing.JTable();
        back = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daily Counts");

        jTabbedPane1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        MonCounts.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mondayList, MonCounts);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entryId}"));
        columnBinding.setColumnName("Entry Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${movementId}"));
        columnBinding.setColumnName("Movement Id");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${timeId}"));
        columnBinding.setColumnName("Time Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${day}"));
        columnBinding.setColumnName("Day");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${date}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lgvCount}"));
        columnBinding.setColumnName("Lgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${hgvCount}"));
        columnBinding.setColumnName("Hgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalVehCount}"));
        columnBinding.setColumnName("Total Veh Count");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        MondayPane.setViewportView(MonCounts);

        jTabbedPane1.addTab("Mon", MondayPane);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tuesdayList, TueCounts);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entryId}"));
        columnBinding.setColumnName("Entry Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${movementId}"));
        columnBinding.setColumnName("Movement Id");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${timeId}"));
        columnBinding.setColumnName("Time Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${day}"));
        columnBinding.setColumnName("Day");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${date}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lgvCount}"));
        columnBinding.setColumnName("Lgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${hgvCount}"));
        columnBinding.setColumnName("Hgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalVehCount}"));
        columnBinding.setColumnName("Total Veh Count");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        TuesdsyPane.setViewportView(TueCounts);

        jTabbedPane1.addTab("Tue", TuesdsyPane);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, wednesdayList, WedCounts);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entryId}"));
        columnBinding.setColumnName("Entry Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${movementId}"));
        columnBinding.setColumnName("Movement Id");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${timeId}"));
        columnBinding.setColumnName("Time Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${day}"));
        columnBinding.setColumnName("Day");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${date}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lgvCount}"));
        columnBinding.setColumnName("Lgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${hgvCount}"));
        columnBinding.setColumnName("Hgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalVehCount}"));
        columnBinding.setColumnName("Total Veh Count");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        WednesdayPane.setViewportView(WedCounts);

        jTabbedPane1.addTab("Wed", WednesdayPane);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, thursdayList, ThuCounts);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entryId}"));
        columnBinding.setColumnName("Entry Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${movementId}"));
        columnBinding.setColumnName("Movement Id");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${timeId}"));
        columnBinding.setColumnName("Time Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${day}"));
        columnBinding.setColumnName("Day");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${date}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lgvCount}"));
        columnBinding.setColumnName("Lgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${hgvCount}"));
        columnBinding.setColumnName("Hgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalVehCount}"));
        columnBinding.setColumnName("Total Veh Count");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        ThursdayPane.setViewportView(ThuCounts);

        jTabbedPane1.addTab("Thur", ThursdayPane);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, fridayList, FriCounts);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entryId}"));
        columnBinding.setColumnName("Entry Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${movementId}"));
        columnBinding.setColumnName("Movement Id");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${timeId}"));
        columnBinding.setColumnName("Time Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${day}"));
        columnBinding.setColumnName("Day");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${date}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lgvCount}"));
        columnBinding.setColumnName("Lgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${hgvCount}"));
        columnBinding.setColumnName("Hgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalVehCount}"));
        columnBinding.setColumnName("Total Veh Count");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        FridayPane.setViewportView(FriCounts);

        jTabbedPane1.addTab("Fri", FridayPane);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, saturdayList, SatCounts);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entryId}"));
        columnBinding.setColumnName("Entry Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${movementId}"));
        columnBinding.setColumnName("Movement Id");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${timeId}"));
        columnBinding.setColumnName("Time Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${day}"));
        columnBinding.setColumnName("Day");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${date}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lgvCount}"));
        columnBinding.setColumnName("Lgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${hgvCount}"));
        columnBinding.setColumnName("Hgv Count");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalVehCount}"));
        columnBinding.setColumnName("Total Veh Count");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        SaturdayPane.setViewportView(SatCounts);

        jTabbedPane1.addTab("Sat", SaturdayPane);

        back.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        back.setText("RETURN");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        print.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        print.setText("PRINT DATA");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daily Counts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
        try {
            new Management().setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(DailyCountsData.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_backActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        PrintDailyCounts pdc = new PrintDailyCounts();
        pdc.fillArray();
        new PrintDailyCounts().setVisible(true);
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DailyCountsData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DailyCountsData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DailyCountsData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DailyCountsData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DailyCountsData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable FriCounts;
    private java.util.List<AutoLightsUI.DailyCounts> FridayList;
    private javax.swing.JScrollPane FridayPane;
    private javax.persistence.Query FridayQuery;
    public javax.swing.JTable MonCounts;
    private java.util.List<AutoLightsUI.DailyCounts> MondayList;
    private javax.swing.JScrollPane MondayPane;
    private javax.persistence.Query MondayQuery;
    public javax.swing.JTable SatCounts;
    private java.util.List<AutoLightsUI.DailyCounts> SaturdayList;
    private javax.swing.JScrollPane SaturdayPane;
    private javax.persistence.Query SaturdayQuery;
    public javax.swing.JTable ThuCounts;
    private java.util.List<AutoLightsUI.DailyCounts> ThursdayList;
    private javax.swing.JScrollPane ThursdayPane;
    private javax.persistence.Query ThursdayQuery;
    public javax.swing.JTable TueCounts;
    private java.util.List<AutoLightsUI.DailyCounts> TuesdayList;
    private javax.persistence.Query TuesdayQuery;
    private javax.swing.JScrollPane TuesdsyPane;
    public javax.swing.JTable WedCounts;
    private java.util.List<AutoLightsUI.DailyCounts> WednesdayList;
    private javax.swing.JScrollPane WednesdayPane;
    private javax.persistence.Query WednesdayQuery;
    private javax.swing.JButton back;
    private java.util.List<AutoLightsUI.DailyCounts> dailyCountsList;
    private java.util.List<AutoLightsUI.DailyCounts> dailyCountsList1;
    private javax.persistence.Query dailyCountsQuery;
    private javax.persistence.Query dailyCountsQuery1;
    private javax.persistence.EntityManager entityManager;
    private javax.persistence.EntityManager entityManager0;
    private java.util.List<AutoLightsUI.Friday> fridayList;
    private javax.persistence.Query fridayQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private java.util.List<AutoLightsUI.Monday> mondayList;
    private javax.persistence.Query mondayQuery;
    private javax.swing.JButton print;
    private java.util.List<AutoLightsUI.Saturday> saturdayList;
    private javax.persistence.Query saturdayQuery;
    private java.util.List<AutoLightsUI.Thursday> thursdayList;
    private javax.persistence.Query thursdayQuery;
    private java.util.List<AutoLightsUI.Tuesday> tuesdayList;
    private javax.persistence.Query tuesdayQuery;
    private java.util.List<AutoLightsUI.Wednesday> wednesdayList;
    private javax.persistence.Query wednesdayQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
